### ISSUE TITLE
TDWG spatial data on ArcGIS online

### ISSUE THREAD

**Issue by stevenpbachman** [tdwg/prior-standards#20]
Apologies, but the link to the spatial data for TDWG from Kew is temporarily down. Until it is fixed you can find the data here >>

TDWG level 1
https://www.maps.arcgis.com/home/item.html?id=cc823903c99d4a8a869479c6e5a9b0cb

TDWG level 2
https://www.maps.arcgis.com/home/item.html?id=5bbe9992d3f043d1834096b852723215

TDWG level 3
https://www.maps.arcgis.com/home/item.html?id=9271fa89adf04301bf3c2614159f1416

TDWG level 4
https://www.maps.arcgis.com/home/item.html?id=22e7b5071e69461d8b6466efff489976

**Comment by peterdesmet** [comment]
Hi @stevenpbachman, thanks for the info. The ArcGIS files for level 1-4 are now part of the repository, which has moved to https://github.com/tdwg/wgsrpd.
