### ISSUE TITLE
standards documentation from twiki migration unreadable 

### ISSUE THREAD

**Issue by wouteraddink** [tdwg/prior-standards#23]
Just want to raise the issue that some of the standards documentation became fairly unreadable by migration of the TDWG TWIKI contents. For instance SDD standard documentation: https://github.com/tdwg/wiki-archive/blob/master/twiki/data/SDD/Primer/SddIntroduction.txt 
You can read it, but all formatting and structure is 'lost'. Will this be taken into account with the new TDWG website?

**Comment by mdoering** [comment]
The wiki is only kept as an archive and not really meant to be a current documentation.
If needed and still current that information should be migrated.

See also tdwg/infrastructure#16
